# Generated by Django 5.2.8 on 2025-11-13 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('short_link', models.CharField(verbose_name='Link encurtado')),
                ('redirect_to', models.URLField(verbose_name='Redirecionar para')),
                ('clicks', models.IntegerField(default=0, verbose_name='Cliques')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
                'ordering': ['title'],
            },
        ),
    ]
